# This file is a template, and might need editing before it works on your project.
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Python.gitlab-ci.yml

# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/
image: docker.team23.de/docker/hub/python:latest

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/topics/caching/
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
cache:
  key:
    files:
      - poetry.lock
      - .gitlab-ci.yml
    prefix: ${CI_JOB_NAME}
  paths:
    - .venv
    - .cache/pip

stages:
  - setup
  - quality
  - tests
  - build
  - deploy

setup:
  - python --version
  - pip install poetry
  - poetry config virtualenvs.in-project true
  - poetry install
  - source `poetry env info --path`/bin/activate

isort:
  stage: quality
  script:
    - poetry run isort --diff --check-only --settings-path pyproject.toml ./

flake8:
   stage: quality
   script:
    - poetry run mypy --config-file pyproject.toml ./

pylint:
  stage: quality
  script:
    - pylint .

safety:
  stage: quality
  script:
    - poetry check
    - poetry run safety check --full-report
    #- poetry run bandit -ll --recursive fastapi_module_loader tests

pytest:
  stage: tests
  script:
    - pytest --junitxml=report.xml --cov=fastapi_module_loader tests/
  artifacts:
    when: always
    reports:
      junit: report.xml

build_package:
  stage: build
  script:
    - poetry build
  artifacts:
    paths:
      - dist
    expire_in: 1 week

documentation:
  stage: deploy
  script:
    - pip install sphinx sphinx-rtd-theme
    - cd doc
    - make html
    - mv _build/html/ ../public/
  artifacts:
    paths:
      - public
  only:
    - tags

deploy-package-gitlab:
  stage: deploy
  only:
    - tag
  dependencies:
    - build_package
  script:
    - poetry config repositories.gitlab "https://git.team23.de/api/v4/projects/$CI_PROJECT_ID/packages/pypi"
    - poetry config http-basic.gitlab gitlab-ci-token "$CI_JOB_TOKEN"
    - poetry publish --repository gitlab
