# This file contains values from Cookiecutter

default_context:
  project_name: "fastapi-module-loader"
  project_description: "FastAPI modules loading for better structure in your projects (like Django AppConfig)"
  organization: "TEAM23 GmbH"
  license: "MIT"
  minimal_python_version: 3.7
  github_name: "team23"
  email: "info@team23.de"
  version: "0.1.0"
  line_length: "120"
  create_example_template: "none"
